export const CLEAR_STORE = 'CLEAR_STORE';

export const PATIENT_SERVER_REQUEST = 'PATIENT_SERVER_REQUEST';
export const PATIENT_UPLOAD_SUCCESS = 'PATIENT_UPLOAD_SUCCESS';
//export const PATIENT_SERVER_SUCCESS = 'PATIENT_SERVER_SUCCESS';
export const PATIENT_SERVER_ERROR = 'PATIENT_SERVER_ERROR';

export const LOAD_BEERS_SUCCESS = 'LOAD_BEERS_SUCCESS';
export const LOAD_BEERS_FAILED = 'LOAD_BEERS_FAILED';
export const USER_SELECT_BEER = 'USER_SELECT_BEER';

export const MANAGE_FAVORITE = 'MANAGE_FAVORITE';
export const LOAD_FAVORITES_SUCCESS = 'LOAD_FAVORITES_SUCCESS';

export const AUTHENTICATE_LOADING = 'AUTHENTICATE_LOADING';
export const AUTHENTICATE_SUCCESS = 'AUTHENTICATE_SUCCESS';
export const AUTHENTICATE_FAILED = 'AUTHENTICATE_FAILED';
