export const CLEAR_STORE = 'CLEAR_STORE';

export const LOAD_BEERS_SUCCESS = 'LOAD_BEERS_SUCCESS';
export const LOAD_BEERS_FAILED = 'LOAD_BEERS_FAILED';
export const USER_SELECT_BEER = 'USER_SELECT_BEER';

export const MANAGE_FAVORITE = 'MANAGE_FAVORITE';
export const LOAD_FAVORITES_SUCCESS = 'LOAD_FAVORITES_SUCCESS';