export const SOCKET_CONNECTION_REQUEST = 'SOCKET_CONNECTION_REQUEST';
export const SOCKET_CONNECTION_ERROR = 'SOCKET_CONNECTION_ERROR';
export const SOCKET_CONNECTION_SUCCESS = 'SOCKET_CONNECTION_SUCCESS';